services:
  jenkins:
    build:
      context: ./jenkins
      args:
        DOCKER_GID: "987"
    container_name: jenkins
    restart: always
    command: --prefix=/ci
    ports:
      - "8081:8080"
      - "50000:50000"
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/kyle/Projects/ai-agent-rag:/home/kyle/Projects/ai-agent-rag
    networks:
      - app_net

volumes:
  jenkins_home:

networks:
  app_net:
    external: true
